# =========================================================
# FONT
# =========================================================
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

disable_ligatures never

# =========================================================
# CURSOR
# =========================================================
cursor_shape beam
cursor_beam_thickness 8

cursor_blink true
cursor_blink_interval 0.6
cursor_stop_blinking_after 0

cursor_trail 1
cursor_trail_decay 0.18 0.35
cursor_trail_start_threshold 1

# =========================================================
# WINDOW
# =========================================================
window_padding_width 7
window_margin_width 5
window_border_width 1

corner_radius 0

# =========================================================
# TRANSPARENCY + BLUR
# =========================================================
background_opacity 0.90

dynamic_background_opacity yes

blur_background yes
blur_radius 20
blur_method dual_kawase

# =========================================================
# TOKYO NIGHT MOON
# =========================================================

foreground #c8d3f5
background #1e2030

selection_foreground #c8d3f5
selection_background #3b4261

url_color #86e1fc

# black
color0  #1b1d2b
color8  #444a73

# red
color1  #ff757f
color9  #ff8b94

# green
color2  #c3e88d
color10 #c7fb6d

# yellow
color3  #ffc777
color11 #ffd580

# blue
color4  #82aaff
color12 #9ab8ff

# magenta
color5  #c099ff
color13 #d2b3ff

# cyan
color6  #86e1fc
color14 #b4f9f8

# white
color7  #c8d3f5
color15 #ffffff

# =========================================================
# CURSOR COLORS
# =========================================================
cursor #ffffff
cursor_text_color background

# =========================================================
# BORDERS
# =========================================================
active_border_color   #86e1fc
inactive_border_color #444a73
bell_border_color     #ff757f

# =========================================================
# TABS
# =========================================================
tab_bar_edge bottom
tab_bar_style hidden
tab_powerline_style slanted
tab_bar_min_tabs 0
placement_strategy center

active_tab_background   #2a2d40
active_tab_foreground   #86e1fc

inactive_tab_background #1e2030
inactive_tab_foreground #565f89

active_tab_font_style bold
inactive_tab_font_style normal

# =========================================================
# MARKS
# =========================================================
mark1_foreground #1e2030
mark1_background #86e1fc

mark2_foreground #1e2030
mark2_background #c099ff

mark3_foreground #1e2030
mark3_background #ffc777

# =========================================================
# BEHAVIOR
# =========================================================
enable_audio_bell no
scrollback_lines 10000
confirm_os_window_close 0