#!/bin/sh

player="spotify"
playerctl -p "$player" status >/dev/null 2>&1 || exit

status=$(playerctl -p "$player" status)
[ "$status" = "Playing" ] || exit

artist=$(playerctl -p "$player" metadata artist)
title=$(playerctl -p "$player" metadata title)

printf " %s - %s" "$artist" "$title"
