#!/usr/bin/env python3

import requests
import subprocess
import os
from datetime import datetime

def getWeatherIcon(isDaytime: bool, weatherCode: int):

    if weatherCode in [0, 1]:
        return "󰖙" if isDaytime else "󰖔"

    if weatherCode == 2:
        return "󰖕"

    if weatherCode == 3:
        return "󰖐"

    if weatherCode in [45, 48]:
        return "󰖑"

    if weatherCode in [51, 53, 55, 56, 57]:
        return "󰖗"

    if weatherCode in [61, 63, 65, 66, 67, 80, 81, 82]:
        return "󰖖"

    if weatherCode in [71, 73, 75, 77, 85, 86]:
        return "󰖘"

    if weatherCode == 95:
        return "󰙾"

    if weatherCode in [96, 99]:
        return "󰙿"

    return "󰖐"

lat, lon = "22.580539", "88.322016"

url = "https://api.open-meteo.com/v1/forecast"

params = {
    "latitude": lat,
    "longitude": lon,
    "current": [
        "temperature_2m",
        "is_day",
        "weather_code",
        "wind_speed_10m",
        "wind_gusts_10m",
        "precipitation_probability"
    ],
    "daily": [
        "temperature_2m_min",
        "temperature_2m_max",
        "weather_code",
        "precipitation_probability_max"
    ],
    "models": "ecmwf_ifs025",
    "timezone": "auto",
    "forecast_days": 8
}

try:
    response = requests.get(url, params=params, timeout=10)
    response.raise_for_status()

    data = response.json()

    current = data["current"]

    temp = current["temperature_2m"]
    code = current["weather_code"]
    is_day = bool(current["is_day"])

    precipitation_prob = current["precipitation_probability"]

    icon = getWeatherIcon(is_day, code)

    current_weather = f"{icon} {round(temp)}°C ☔ {precipitation_prob}%"

    daily = data["daily"]

    days = daily["time"][1:8]
    max_temps = daily["temperature_2m_max"][1:8]
    min_temps = daily["temperature_2m_min"][1:8]
    codes = daily["weather_code"][1:8]
    precip_max = daily["precipitation_probability_max"][1:8]

    if os.getenv("BLOCK_BUTTON") == "1":

        forecast = ""

        for i in range(7):
            day_label = datetime.strptime(
                days[i],
                "%Y-%m-%d"
            ).strftime("%a")

            day_icon = getWeatherIcon(True, codes[i])

            forecast += (
                f"{day_label:<4} "
                f"{day_icon}  "
                f"{round(min_temps[i])}°/"
                f"{round(max_temps[i])}°  "
                f"☔ {precip_max[i]}%\n"
            )

        subprocess.run([
            "notify-send",
            "󰖙 7-Day Forecast",
            forecast,
            "-u", "low",
            "-t", "5000"
        ])

    print(current_weather)

except Exception:
    print("󰖐 --°C")